version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # location of requirements.txt
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/client" #where package.json lives
    schedule:
      interval: "daily"
